version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: leetlab_postgres
    restart: always
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: eC4NqMJxTbmfG22zfPdUtdLkgsbDjwdS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: leetlab_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass R9GTr6ELknQz3LK3PyaqVWNdFydySwxt

  judge0-api:
    image: judge0/judge0:1.13.0
    container_name: leetlab_judge0
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "2358:2358"
    environment:
      - DATABASE_URL=postgresql://judge0:eC4NqMJxTbmfG22zfPdUtdLkgsbDjwdS@postgres:5432/judge0
      - REDIS_URL=redis://default:R9GTr6ELknQz3LK3PyaqVWNdFydySwxt@redis:6379
      - ENABLE_AUTH=false
      - RAILS_ENV=production
      - ENABLE_EXTRA_LANGUAGES=true

volumes:
  postgres_data:
